<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PhoneBook.DAL\PhoneBook.DAL.csproj" />
      <ProjectReference Include="..\PhoneBook.Model\PhoneBook.Model.csproj" />
    </ItemGroup>

</Project>
